<?php
$page = 2075;
if($myVariable) {
    $page = $myVariable;
}
$thumbnail = get_the_post_thumbnail_url( $page );

if($thumbnail) {
?>
<div class="relative slider">
    <div class="img_container">
        <!-- Image Map Generated by http://www.image-map.net/ -->
        <img src="<?=$thumbnail?>" usemap="#image-map" class="img_exclude map shared-values">

        <map name="image-map" id="image-map" name="map">
        <area target="" alt="Compassion" title="Compassion" href="" coords="126,289,124,270,123,242,127,207,134,178,147,146,159,124,174,102,195,77,210,63,227,49,246,37,263,29,286,25,310,24,336,34,354,48,367,61,378,71,386,84,373,81,362,87,359,100,353,116,347,133,340,144,332,157,324,168,312,174,293,182,276,186,256,187,240,186,219,187,203,192,186,202,166,213,152,223,141,236,133,251,130,263" shape="poly">
        <area target="" alt="Teamwork" title="Teamwork" href="" coords="252,33,282,19,312,11,335,4,371,1,397,3,431,7,469,20,501,35,526,52,550,73,563,92,570,117,571,144,563,169,557,183,543,206,537,213,537,196,531,193,524,190,510,190,497,190,474,189,454,184,441,177,431,168,423,158,415,151,406,137,402,119,397,106,391,93,384,80,379,70,368,59,356,49,342,36,323,29,308,21,289,23" shape="poly">
        <area target="" alt="Innovation" title="Innovation" href="" coords="552,74,567,100,573,130,570,150,564,169,557,186,545,203,536,216,520,230,499,245,484,259,473,278,466,299,466,326,474,347,480,361,482,377,481,386,471,392,464,394,481,401,500,404,520,406,538,406,558,400,575,391,592,375,602,362,620,318,627,271,628,236,623,206,616,174,604,145,591,121,578,102" shape="poly">
        <area target="" alt="Integrity" title="Integrity" href="" coords="268,380,275,390,288,395,299,390,313,377,322,370,336,362,349,357,368,352,385,352,402,359,414,363,435,375,452,389,467,398,489,404,516,406,537,407,563,399,584,385,600,369,580,401,564,418,543,439,529,452,504,471,481,480,461,489,431,499,405,501,385,503,365,503,348,502,336,501,317,495,302,482,290,471,278,456,270,437,267,417,265,398" shape="poly">
        <area target="" alt="Partnership" title="Partnership" href="" coords="223,190,215,196,212,205,214,214,223,221,233,228,245,238,255,246,263,253,270,265,278,279,283,296,283,318,280,340,274,351,271,364,267,378,266,390,266,410,270,435,280,460,294,476,310,489,318,497,294,491,270,480,248,470,229,457,208,441,192,426,176,404,157,379,148,360,139,337,132,318,128,302,128,288,131,265,138,245,154,223,185,202,204,191" shape="poly">
        </map>
    </div>
</div>
<style>
    div.map {
        width: 100% !important;
        background-size: cover;
        BACKGROUND-REPEAT: no-repeat;
    }
    div.map canvas {
        width: 100% !important;
    }
</style>
<script> 
jQuery(document).ready(function(){
    jQuery('.shared-values').maphilight({
        fillColor:'FFFFFF',
        fillOpacity: 0.5,
        stroke: false,
    }); 
    jQuery('.slider').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        infinite: false,
        dots: false,
        centerMode: true,
        focusOnSelect: true,
        arrows: false,
        prevArrow: "<div class='pointer slick-nav left prev absolute'><div class='absolute position-center-center'><i class='fa fa-chevron-left fa-2em'></i></div></div>",
        nextArrow: "<div class='pointer slick-nav right next absolute'><div class='absolute position-center-center'><i class='fa fa-chevron-right fa-2em'></i></div></div>",
    }); 
});

</script>
<?php } ?>